console.log("My first console project"); 
var first_name = "Pavan"; 
var last_name = "Borade"; 
var full_name = first_name.concat(last_name); 
console.log(full_name); 
var a = 100; 
var b = 20; 
var add = a + b ; 
console.log(add); 
var sub = a - b ; 
console.log(sub); 
var multiply = a * b ; 
console.log(multiply); 
var divide = a / b ; 
console.log(divide);